Repository hash-checker/hash-checker-lite, pull requests merged in 2021-05, with the labels that each got.

#54 2021-05-07 v. 1.0.7: added @vipozdn to Contributors
  README.md
Labels: documentation

#58 1.0.8
  .gitignore
  README.md
Labels: documentation

#61 2021-05-10 v. 1.0.8: improved Code Quality
  app/src/androidTest/java/com/smlnskgmail/jaman/hashcheckerlite/AndroidTestSuite.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashcheckerlite/components/BaseUITest.java
  app/src/androidTest/java/com/smlnskgmail/jaman/hashcheckerlite/runner/AndroidJacocoTestRunner.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/App.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/MainActivity.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/components/BaseFragment.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/components/bottomsheets/lists/adapter/BaseListHolder.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/components/dialogs/system/AppProgressDialog.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/components/watchers/AppTextWatcher.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/feedback/FeedbackFragment.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/HashCalculatorTask.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/jdk/JdkHashCalculator.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/jdk/JdkHashCalculatorDigest.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/jdk/JdkHashUtils.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/ui/HashCalculatorFragment.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/ui/TextUtils.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/ui/lists/actions/ui/ActionSelectActionsBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/ui/lists/actions/ui/ActionsBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/ui/lists/actions/ui/SourceSelectActionsBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/ui/lists/hashtypes/GenerateToBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/impl/SharedPreferencesSettingsHelper.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/ui/SettingsFragment.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/ui/lists/languages/LanguagesBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/ui/lists/languages/LanguagesListAdapter.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/ui/lists/themes/ThemesBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/ui/lists/themes/ThemesListAdapter.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/ui/lists/weblinks/AuthorWebLinksBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/ui/lists/weblinks/PrivacyPolicyWebLinksBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/ui/lists/weblinks/WebLinksBottomSheet.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/utils/LogUtils.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/utils/RestartUtils.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/utils/WebUtils.java
  app/src/test/java/com/smlnskgmail/jaman/hashcheckerlite/calculator/jdk/JdkHashUtilsTest.java
  app/src/test/java/com/smlnskgmail/jaman/hashcheckerlite/tools/TextUtilsTest.java
Labels: code format

#67 2021-05-16 v. 1.0.8: updated documentation
  README.md
Labels: documentation

#68 2021-05-16 v. 1.0.8: updated documentation
  README.md
Labels: documentation

#71 2021-05-19 v. 1.0.8: Fix CDP issues
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/settings/ui/SettingsFragment.java
Labels: code format

#72 2021-05-23 v. 1.0.8: updated app description
  README.md
Labels: documentation

#73 2021-05-23 v. 1.0.8: updated app description
  README.md
Labels: documentation

#74 2021-05-25 v. 1.0.8: updated documentation
  README.md
Labels: documentation

#66 exit on double back pressing added
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/MainActivity.java
  app/src/main/java/com/smlnskgmail/jaman/hashcheckerlite/logic/hashcalculator/ui/HashCalculatorFragment.java
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement

#77 2021-05-30 v. 1.0.8: added @yasin459 to Contributors
  README.md
Labels: documentation
